services:
  - type: web
    name: book-review-project-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 backend.app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: book-review-project-db
          property: connectionString
      - key: SECRET_KEY
        genereateValue: true

databases:
  - name: book-review-db
    plan: free
