services:
  - type: web
    name: book-review-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn -w 4 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: book-review-db
          property: connectionString

databases:
  - name: book-review-db
    plan: free
